---
- name: Install Docker, Git & Python3
  hosts: app
  become: true

  tasks:
    - name: Download docker.sh
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "+x"

    - name: Install docker
      shell: sh /tmp/get-docker.sh
      run_once: true
    - name: Install Git & Python3
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3
